apiVersion: v1
kind: Pod
metadata:
  name: monlat-agent-1
spec:
  serviceAccount: monlat
  containers:
  - name: ping-container
    image: portainer/kubectl-shell:latest
    securityContext:
      runAsUser: 0
      runAsGroup: 0
    command:
    - /bin/sh
    - -c
    - |
      sleep 5
      nodeName_pod1=$(kubectl get pod monlat-agent-1 -o jsonpath={.spec.nodeName})
      while [ -z "$nodeName_pod1" ]; do
        sleep 1
        nodeName_pod1=$(kubectl get pod monlat-agent-1 -o jsonpath={.spec.nodeName})
      done
              IP2=$(kubectl get pod monlat-agent-2 -o jsonpath={.status.podIP}) && nodeName_pod2=$(kubectl get pod monlat-agent-2 -o jsonpath={.spec.nodeName})"; 
        IP3=$(kubectl get pod monlat-agent-3 -o jsonpath={.status.podIP}) && nodeName_pod3=$(kubectl get pod monlat-agent-3 -o jsonpath={.spec.nodeName})"; 
      count=0
      while true; do
                IP2=$(kubectl get pod monlat-agent-2 -o jsonpath={.status.podIP}) && nodeName_pod2=$(kubectl get pod monlat-agent-2 -o jsonpath={.spec.nodeName}) && echo "latency_between_nodes{from=\"$nodeName_pod1\",to=\"$nodeName_pod2\"} $(ping -c 1 $IP2 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        IP3=$(kubectl get pod monlat-agent-3 -o jsonpath={.status.podIP}) && nodeName_pod3=$(kubectl get pod monlat-agent-3 -o jsonpath={.spec.nodeName}) && echo "latency_between_nodes{from=\"$nodeName_pod1\",to=\"$nodeName_pod3\"} $(ping -c 1 $IP3 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        count=$((count+1))
        if [ "$count" -eq 10 ]; then break; fi
        sleep 1;
      done
      while true; do
                echo "latency_between_nodes{from=\"$nodeName_pod1\",to=\"$nodeName_pod2\"} $(ping -c 1 $IP2 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        echo "latency_between_nodes{from=\"$nodeName_pod1\",to=\"$nodeName_pod3\"} $(ping -c 1 $IP3 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        sleep 1;
      done
  nodeSelector:
    monlat-node: node1
---
apiVersion: v1
kind: Pod
metadata:
  name: monlat-agent-2
spec:
  serviceAccount: monlat
  containers:
  - name: ping-container
    image: portainer/kubectl-shell:latest
    securityContext:
      runAsUser: 0
      runAsGroup: 0
    command:
    - /bin/sh
    - -c
    - |
      sleep 5
      nodeName_pod2=$(kubectl get pod monlat-agent-2 -o jsonpath={.spec.nodeName})
      while [ -z "$nodeName_pod2" ]; do
        sleep 1
        nodeName_pod2=$(kubectl get pod monlat-agent-2 -o jsonpath={.spec.nodeName})
      done
              IP1=$(kubectl get pod monlat-agent-1 -o jsonpath={.status.podIP}) && nodeName_pod1=$(kubectl get pod monlat-agent-1 -o jsonpath={.spec.nodeName})"; 
        IP3=$(kubectl get pod monlat-agent-3 -o jsonpath={.status.podIP}) && nodeName_pod3=$(kubectl get pod monlat-agent-3 -o jsonpath={.spec.nodeName})"; 
      count=0
      while true; do
                IP1=$(kubectl get pod monlat-agent-1 -o jsonpath={.status.podIP}) && nodeName_pod1=$(kubectl get pod monlat-agent-1 -o jsonpath={.spec.nodeName}) && echo "latency_between_nodes{from=\"$nodeName_pod2\",to=\"$nodeName_pod1\"} $(ping -c 1 $IP1 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        IP3=$(kubectl get pod monlat-agent-3 -o jsonpath={.status.podIP}) && nodeName_pod3=$(kubectl get pod monlat-agent-3 -o jsonpath={.spec.nodeName}) && echo "latency_between_nodes{from=\"$nodeName_pod2\",to=\"$nodeName_pod3\"} $(ping -c 1 $IP3 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        count=$((count+1))
        if [ "$count" -eq 10 ]; then break; fi
        sleep 1;
      done
      while true; do
                echo "latency_between_nodes{from=\"$nodeName_pod2\",to=\"$nodeName_pod1\"} $(ping -c 1 $IP1 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        echo "latency_between_nodes{from=\"$nodeName_pod2\",to=\"$nodeName_pod3\"} $(ping -c 1 $IP3 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        sleep 1;
      done
  nodeSelector:
    monlat-node: node2
---
apiVersion: v1
kind: Pod
metadata:
  name: monlat-agent-3
spec:
  serviceAccount: monlat
  containers:
  - name: ping-container
    image: portainer/kubectl-shell:latest
    securityContext:
      runAsUser: 0
      runAsGroup: 0
    command:
    - /bin/sh
    - -c
    - |
      sleep 5
      nodeName_pod3=$(kubectl get pod monlat-agent-3 -o jsonpath={.spec.nodeName})
      while [ -z "$nodeName_pod3" ]; do
        sleep 1
        nodeName_pod3=$(kubectl get pod monlat-agent-3 -o jsonpath={.spec.nodeName})
      done
              IP1=$(kubectl get pod monlat-agent-1 -o jsonpath={.status.podIP}) && nodeName_pod1=$(kubectl get pod monlat-agent-1 -o jsonpath={.spec.nodeName})"; 
        IP2=$(kubectl get pod monlat-agent-2 -o jsonpath={.status.podIP}) && nodeName_pod2=$(kubectl get pod monlat-agent-2 -o jsonpath={.spec.nodeName})"; 
      count=0
      while true; do
                IP1=$(kubectl get pod monlat-agent-1 -o jsonpath={.status.podIP}) && nodeName_pod1=$(kubectl get pod monlat-agent-1 -o jsonpath={.spec.nodeName}) && echo "latency_between_nodes{from=\"$nodeName_pod3\",to=\"$nodeName_pod1\"} $(ping -c 1 $IP1 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        IP2=$(kubectl get pod monlat-agent-2 -o jsonpath={.status.podIP}) && nodeName_pod2=$(kubectl get pod monlat-agent-2 -o jsonpath={.spec.nodeName}) && echo "latency_between_nodes{from=\"$nodeName_pod3\",to=\"$nodeName_pod2\"} $(ping -c 1 $IP2 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        count=$((count+1))
        if [ "$count" -eq 10 ]; then break; fi
        sleep 1;
      done
      while true; do
                echo "latency_between_nodes{from=\"$nodeName_pod3\",to=\"$nodeName_pod1\"} $(ping -c 1 $IP1 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        echo "latency_between_nodes{from=\"$nodeName_pod3\",to=\"$nodeName_pod2\"} $(ping -c 1 $IP2 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        sleep 1;
      done
  nodeSelector:
    monlat-node: node3
---
