apiVersion: v1
kind: Pod
metadata:
  name: monitor-latency-agent-1
spec:
  serviceAccount: monitor-latency
  containers:
  - name: ping-container
    image: portainer/kubectl-shell:latest
    securityContext:
      runAsUser: 0
      runAsGroup: 0
    command:
    - /bin/sh
    - -c
    - |
      sleep 3
      while true; do
                IP2=$(kubectl get pod monitor-latency-agent-2 -o jsonpath={.status.podIP}) && echo "latency_between_nodes{from=\"node1\",to=\"node2\"} $(ping -c 1 $IP2 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        IP3=$(kubectl get pod monitor-latency-agent-3 -o jsonpath={.status.podIP}) && echo "latency_between_nodes{from=\"node1\",to=\"node3\"} $(ping -c 1 $IP3 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        sleep 2;
      done
  nodeSelector:
    monitor-latency-node: node1
---
apiVersion: v1
kind: Pod
metadata:
  name: monitor-latency-agent-2
spec:
  serviceAccount: monitor-latency
  containers:
  - name: ping-container
    image: portainer/kubectl-shell:latest
    securityContext:
      runAsUser: 0
      runAsGroup: 0
    command:
    - /bin/sh
    - -c
    - |
      sleep 3
      while true; do
                IP1=$(kubectl get pod monitor-latency-agent-1 -o jsonpath={.status.podIP}) && echo "latency_between_nodes{from=\"node2\",to=\"node1\"} $(ping -c 1 $IP1 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        IP3=$(kubectl get pod monitor-latency-agent-3 -o jsonpath={.status.podIP}) && echo "latency_between_nodes{from=\"node2\",to=\"node3\"} $(ping -c 1 $IP3 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        sleep 2;
      done
  nodeSelector:
    monitor-latency-node: node2
---
apiVersion: v1
kind: Pod
metadata:
  name: monitor-latency-agent-3
spec:
  serviceAccount: monitor-latency
  containers:
  - name: ping-container
    image: portainer/kubectl-shell:latest
    securityContext:
      runAsUser: 0
      runAsGroup: 0
    command:
    - /bin/sh
    - -c
    - |
      sleep 3
      while true; do
                IP1=$(kubectl get pod monitor-latency-agent-1 -o jsonpath={.status.podIP}) && echo "latency_between_nodes{from=\"node3\",to=\"node1\"} $(ping -c 1 $IP1 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        IP2=$(kubectl get pod monitor-latency-agent-2 -o jsonpath={.status.podIP}) && echo "latency_between_nodes{from=\"node3\",to=\"node2\"} $(ping -c 1 $IP2 | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')"; 
        sleep 2;
      done
  nodeSelector:
    monitor-latency-node: node3
---
