apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-latency
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitor-latency
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-latency
  namespace: default
subjects:
- kind: ServiceAccount
  name: monitor-latency
  namespace: default
roleRef:
  kind: Role
  name: monitor-latency
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitor-latency
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitor-latency
subjects:
- kind: ServiceAccount
  name: monitor-latency
  namespace: default
roleRef:
  kind: ClusterRole
  name: monitor-latency
  apiGroup: rbac.authorization.k8s.io
---
